"""
Kirnberger's Musical Dice Game Generator
A demo of algorithmic composition where music is generated by selecting
from pre-composed melodic variants.

Structure:
- Period 1: 6 bars (C major)
- Period 2: 8 bars
- Total: 14 bars
- Each bar has 11 possible melodic variants
- Harmony is fixed for each measure

Features:
1. Sample Mozart-style melodic data
2. MIDI output generation
3. Interactive mode
4. Complete musical implementation
"""

import random
import json
import os
from typing import List, Dict, Tuple, Optional

try:
    from music21 import stream, note, chord, tempo, meter, key, midi
    MUSIC21_AVAILABLE = True
except ImportError:
    MUSIC21_AVAILABLE = False
    print("Warning: music21 not installed. MIDI generation will be unavailable.")
    print("Install with: pip install music21")


class KirnbergerGame:
    """
    Implements Kirnberger's musical dice game with fixed harmony and variable melody.
    """

    def __init__(self):
        self.composition_data = self._initialize_composition_data()
        self.key_signature = 'C'  # C major
        self.time_signature = '3/8'  # Common for minuets

    def _initialize_composition_data(self) -> Dict:
        """
        Initialize the composition data with actual Mozart-style melodic variants.
        Each variant is represented as a list of (note, duration) tuples.
        Duration is in quarter note lengths (0.25=16th, 0.5=8th, 1.0=quarter, etc.)
        Each bar in 3/8 time should total 1.5 quarter lengths.
        """
        data = {}

        # Period 1 (bars 1-6)
        # Bar 1 - I (C major) - Opening, should be confident and clear
        data[1] = {
            'harmony': 'I',
            'chord_notes': ['C4', 'E4', 'G4'],
            'variants': [
                [('C5', 0.5), ('D5', 0.5), ('E5', 0.5)],      # Even eighths
                [('G5', 0.75), ('E5', 0.25), ('C5', 0.5)],    # Dotted rhythm
                [('E5', 0.5), ('D5', 0.5), ('C5', 0.5)],      # Graceful descent
                [('C5', 0.25), ('E5', 0.25), ('G5', 1.0)],    # Quick arpeggio to long note
                [('G4', 1.0), ('C5', 0.25), ('E5', 0.25)],    # Long then quick
                [('E5', 0.5), ('G5', 0.75), ('E5', 0.25)],    # Syncopated neighbor
                [('C5', 0.25), ('B4', 0.25), ('C5', 1.0)],    # Trill-like start
                [('G5', 0.5), ('F5', 0.25), ('E5', 0.75)],    # Uneven descent
                [('C5', 0.75), ('C5', 0.25), ('D5', 0.5)],    # Dotted repeat
                [('E5', 0.25), ('F5', 0.25), ('G5', 1.0)],    # Quick rise to held note
                [('G4', 0.5), ('A4', 0.5), ('B4', 0.5)]       # Even stepwise
            ]
        }

        # Bar 2 - V (G major) - Dominant, creates tension
        data[2] = {
            'harmony': 'V',
            'chord_notes': ['G4', 'B4', 'D5'],
            'variants': [
                [('D5', 0.5), ('C5', 0.5), ('B4', 0.5)],      # Even descent
                [('G4', 0.5), ('A4', 0.25), ('B4', 0.75)],    # Rising with emphasis
                [('B4', 0.25), ('C5', 0.25), ('D5', 1.0)],    # Quick rise to tension
                [('D5', 0.75), ('E5', 0.25), ('F5', 0.5)],    # Syncopated tension
                [('G4', 0.25), ('B4', 0.25), ('D5', 1.0)],    # Arpeggio flourish
                [('B4', 0.5), ('A4', 0.5), ('G4', 0.5)],      # Even descent
                [('D5', 1.0), ('D5', 0.25), ('C5', 0.25)],    # Long then quick
                [('G5', 0.75), ('F5', 0.25), ('D5', 0.5)],    # Dramatic drop
                [('B4', 0.5), ('D5', 0.75), ('B4', 0.25)],    # Rhythmic oscillation
                [('D5', 0.5), ('B4', 0.25), ('G4', 0.75)],    # Cascading down
                [('F5', 0.25), ('E5', 0.25), ('D5', 1.0)]     # Chromatic resolution
            ]
        }

        # Bar 3 - vi (A minor)
        data[3] = {
            'harmony': 'vi',
            'chord_notes': ['A4', 'C5', 'E5'],
            'variants': [
                [('A4', 0.5), ('C5', 0.5), ('E5', 0.5)],
                [('C5', 0.75), ('E5', 0.25), ('A5', 0.5)],
                [('E5', 0.5), ('C5', 0.5), ('A4', 0.5)],
                [('A4', 0.25), ('E5', 1.0), ('C5', 0.25)],
                [('C5', 0.5), ('A4', 0.75), ('E5', 0.25)],
                [('E5', 1.0), ('E5', 0.25), ('C5', 0.25)],
                [('A5', 0.75), ('E5', 0.25), ('C5', 0.5)],
                [('C5', 0.5), ('C5', 0.25), ('E5', 0.75)],
                [('E5', 0.25), ('A4', 0.25), ('C5', 1.0)],
                [('A4', 0.75), ('A4', 0.25), ('C5', 0.5)],
                [('C5', 0.5), ('E5', 0.75), ('C5', 0.25)]
            ]
        }

        # Bar 4 - IV (F major)
        data[4] = {
            'harmony': 'IV',
            'chord_notes': ['F4', 'A4', 'C5'],
            'variants': [
                [('F4', 0.5), ('A4', 0.5), ('C5', 0.5)],
                [('A4', 0.75), ('C5', 0.25), ('F5', 0.5)],
                [('C5', 0.5), ('A4', 0.5), ('F4', 0.5)],
                [('F4', 0.25), ('C5', 1.0), ('A4', 0.25)],
                [('A4', 0.5), ('F4', 0.75), ('C5', 0.25)],
                [('C5', 1.0), ('C5', 0.25), ('A4', 0.25)],
                [('F5', 0.75), ('C5', 0.25), ('A4', 0.5)],
                [('A4', 0.5), ('A4', 0.25), ('C5', 0.75)],
                [('C5', 0.25), ('F4', 0.25), ('A4', 1.0)],
                [('F4', 0.75), ('F4', 0.25), ('A4', 0.5)],
                [('A4', 0.5), ('C5', 0.75), ('A4', 0.25)]
            ]
        }

        # Bar 5 - V (G major) - Approaching first cadence
        data[5] = {
            'harmony': 'V',
            'chord_notes': ['G4', 'B4', 'D5'],
            'variants': [
                [('D5', 0.5), ('C5', 0.5), ('B4', 0.5)],
                [('B4', 0.75), ('D5', 0.25), ('G5', 0.5)],
                [('G4', 0.25), ('B4', 0.25), ('D5', 1.0)],
                [('D5', 1.0), ('D5', 0.25), ('C5', 0.25)],
                [('B4', 0.5), ('G4', 0.75), ('D5', 0.25)],
                [('D5', 0.5), ('B4', 0.5), ('G4', 0.5)],
                [('G5', 0.75), ('D5', 0.25), ('C5', 0.5)],
                [('B4', 0.5), ('B4', 0.25), ('D5', 0.75)],
                [('D5', 0.25), ('G4', 0.25), ('B4', 1.0)],
                [('G4', 0.75), ('D5', 0.5), ('D5', 0.25)],
                [('B4', 0.5), ('D5', 0.75), ('C5', 0.25)]
            ]
        }

        # Bar 6 - I (C major) - HALF CADENCE! Strong period ending
        # All variants end with substantial duration (0.75 or more) for clear phrase closure
        data[6] = {
            'harmony': 'I',
            'chord_notes': ['C4', 'E4', 'G4'],
            'variants': [
                [('D5', 0.25), ('C5', 0.25), ('C5', 1.0)],      # Quick approach, WHOLE NOTE resolution
                [('E5', 0.5), ('D5', 0.25), ('C5', 0.75)],      # Classic descent with emphasis
                [('G5', 0.5), ('C5', 1.0)],                     # Dramatic leap to WHOLE NOTE
                [('B4', 0.25), ('C5', 1.25)],                   # Leading tone to VERY LONG tonic
                [('F5', 0.25), ('E5', 0.25), ('C5', 1.0)],      # Suspension to WHOLE NOTE
                [('D5', 0.5), ('D5', 0.25), ('C5', 0.75)],      # Emphatic repeated approach
                [('C5', 1.5)],                                   # Single sustained FULL BAR (strong!)
                [('E5', 0.75), ('C5', 0.75)],                   # Two-note strong cadence
                [('G4', 0.25), ('B4', 0.25), ('C5', 1.0)],      # Rising to WHOLE NOTE
                [('A4', 0.25), ('B4', 0.25), ('C5', 1.0)],      # Stepwise to WHOLE NOTE
                [('C5', 0.5), ('C5', 1.0)]                      # Repeated tonic to WHOLE NOTE
            ]
        }

        # Period 2 (bars 7-14)
        # Bar 7 - I (C major) - Fresh start of period 2
        data[7] = {
            'harmony': 'I',
            'chord_notes': ['C4', 'E4', 'G4'],
            'variants': [
                [('C5', 0.5), ('D5', 0.5), ('E5', 0.5)],
                [('G4', 0.75), ('C5', 0.25), ('E5', 0.5)],
                [('E5', 0.5), ('G5', 0.75), ('C5', 0.25)],
                [('C5', 0.25), ('E5', 1.0), ('D5', 0.25)],
                [('G4', 0.5), ('E5', 0.5), ('C5', 0.5)],
                [('E5', 0.75), ('C5', 0.25), ('G4', 0.5)],
                [('C5', 0.25), ('G4', 0.25), ('E5', 1.0)],
                [('G5', 0.75), ('E5', 0.25), ('G4', 0.5)],
                [('E5', 0.5), ('C5', 0.5), ('C5', 0.5)],
                [('C5', 1.0), ('C5', 0.25), ('E5', 0.25)],
                [('G4', 0.5), ('G4', 0.25), ('C5', 0.75)]
            ]
        }

        # Bar 8 - V (G major)
        data[8] = {
            'harmony': 'V',
            'chord_notes': ['G4', 'B4', 'D5'],
            'variants': [
                [('D5', 0.5), ('E5', 0.25), ('F5', 0.75)],
                [('B4', 0.75), ('D5', 0.25), ('G5', 0.5)],
                [('G4', 0.25), ('B4', 0.25), ('D5', 1.0)],
                [('D5', 0.5), ('B4', 0.75), ('G5', 0.25)],
                [('B4', 0.5), ('D5', 0.5), ('F5', 0.5)],
                [('G5', 0.75), ('D5', 0.25), ('B4', 0.5)],
                [('D5', 1.0), ('D5', 0.25), ('B4', 0.25)],
                [('B4', 0.5), ('G4', 0.75), ('D5', 0.25)],
                [('G4', 0.75), ('D5', 0.25), ('B4', 0.5)],
                [('D5', 0.25), ('F5', 0.75), ('D5', 0.5)],
                [('B4', 0.5), ('B4', 0.25), ('G5', 0.75)]
            ]
        }

        # Bar 9 - vi (A minor)
        data[9] = {
            'harmony': 'vi',
            'chord_notes': ['A4', 'C5', 'E5'],
            'variants': [
                [('E5', 0.5), ('F5', 0.25), ('E5', 0.75)],
                [('C5', 0.75), ('E5', 0.25), ('A5', 0.5)],
                [('A4', 0.5), ('C5', 0.5), ('E5', 0.5)],
                [('E5', 0.25), ('C5', 0.75), ('A5', 0.5)],
                [('C5', 0.5), ('A4', 0.75), ('E5', 0.25)],
                [('A5', 0.75), ('E5', 0.25), ('C5', 0.5)],
                [('E5', 1.0), ('E5', 0.25), ('A4', 0.25)],
                [('C5', 0.5), ('C5', 0.25), ('E5', 0.75)],
                [('A4', 0.75), ('E5', 0.25), ('C5', 0.5)],
                [('E5', 0.5), ('A5', 0.75), ('E5', 0.25)],
                [('C5', 0.5), ('E5', 1.0)]
            ]
        }

        # Bar 10 - iii (E minor)
        data[10] = {
            'harmony': 'iii',
            'chord_notes': ['E4', 'G4', 'B4'],
            'variants': [
                [('E5', 0.5), ('D5', 0.5), ('C5', 0.5)],
                [('G4', 0.75), ('B4', 0.25), ('E5', 0.5)],
                [('B4', 0.5), ('E5', 0.75), ('G5', 0.25)],
                [('E5', 0.25), ('G4', 0.75), ('B4', 0.5)],
                [('G4', 0.5), ('E5', 0.5), ('D5', 0.5)],
                [('B4', 0.5), ('B4', 0.25), ('E5', 0.75)],
                [('E5', 1.0), ('E5', 0.25), ('D5', 0.25)],
                [('G5', 0.75), ('E5', 0.25), ('B4', 0.5)],
                [('B4', 0.5), ('D5', 0.25), ('E5', 0.75)],
                [('E5', 0.75), ('B4', 0.25), ('G4', 0.5)],
                [('G4', 0.5), ('G4', 0.25), ('B4', 0.75)]
            ]
        }

        # Bar 11 - IV (F major) - Building toward cadence
        data[11] = {
            'harmony': 'IV',
            'chord_notes': ['F4', 'A4', 'C5'],
            'variants': [
                [('C5', 0.5), ('D5', 0.25), ('E5', 0.75)],
                [('A4', 0.75), ('C5', 0.25), ('F5', 0.5)],
                [('F4', 0.5), ('A4', 0.5), ('C5', 0.5)],
                [('C5', 0.25), ('A4', 0.75), ('F5', 0.5)],
                [('A4', 0.5), ('F4', 0.75), ('C5', 0.25)],
                [('F5', 0.75), ('C5', 0.25), ('D5', 0.5)],
                [('C5', 1.0), ('C5', 0.25), ('E5', 0.25)],
                [('A4', 0.5), ('A4', 0.25), ('C5', 0.75)],
                [('F4', 0.75), ('C5', 0.25), ('A4', 0.5)],
                [('C5', 0.5), ('E5', 0.75), ('F5', 0.25)],
                [('A4', 0.5), ('C5', 1.0)]
            ]
        }

        # Bar 12 - I6/4 (C major second inversion) - Cadential 6/4
        data[12] = {
            'harmony': 'I6/4',
            'chord_notes': ['G4', 'C5', 'E5'],
            'variants': [
                [('F5', 0.5), ('E5', 0.5), ('D5', 0.5)],
                [('E5', 0.75), ('D5', 0.25), ('C5', 0.5)],
                [('D5', 0.5), ('E5', 0.25), ('F5', 0.75)],
                [('E5', 1.0), ('E5', 0.25), ('D5', 0.25)],
                [('D5', 0.5), ('C5', 0.5), ('D5', 0.5)],
                [('F5', 0.75), ('F5', 0.25), ('E5', 0.5)],
                [('E5', 0.5), ('F5', 0.75), ('E5', 0.25)],
                [('D5', 0.5), ('D5', 0.25), ('E5', 0.75)],
                [('E5', 0.25), ('C5', 0.75), ('D5', 0.5)],
                [('F5', 0.5), ('D5', 0.5), ('E5', 0.5)],
                [('E5', 0.5), ('E5', 0.5), ('E5', 0.5)]
            ]
        }

        # Bar 13 - V (G major) - DOMINANT! Final approach to cadence!
        data[13] = {
            'harmony': 'V',
            'chord_notes': ['G4', 'B4', 'D5'],
            'variants': [
                [('D5', 0.5), ('C5', 0.25), ('B4', 0.75)],      # Strong leading tone emphasis
                [('B4', 0.25), ('C5', 0.25), ('D5', 1.0)],      # Rising tension held
                [('F5', 0.75), ('E5', 0.25), ('D5', 0.5)],      # Dramatic high descent
                [('D5', 1.0), ('D5', 0.25), ('B4', 0.25)],      # Sustained tension
                [('B4', 0.5), ('A4', 0.25), ('B4', 0.75)],      # Neighbor to strong leading tone
                [('D5', 0.25), ('E5', 0.25), ('F5', 1.0)],      # Building to peak
                [('G5', 0.75), ('F5', 0.25), ('D5', 0.5)],      # Grand descent
                [('B4', 0.75), ('D5', 0.5), ('B4', 0.25)],      # Rhythmic tension
                [('D5', 0.5), ('F5', 0.75), ('D5', 0.25)],      # Wide leap emphasis
                [('A4', 0.25), ('B4', 0.25), ('C5', 1.0)],      # Chromatic rise to tension
                [('F5', 0.5), ('D5', 0.25), ('B4', 0.75)]       # Cascading to leading tone
            ]
        }

        # Bar 14 - I (C major) - FINAL CADENCE!!! Grand, conclusive resolution!
        # ALL variants end with WHOLE NOTE or longer for maximum finality
        data[14] = {
            'harmony': 'I',
            'chord_notes': ['C4', 'E4', 'G4'],
            'variants': [
                [('C5', 1.5)],                                   # Single sustained tonic - ultimate finality!
                [('E5', 0.25), ('D5', 0.25), ('C5', 1.0)],      # Graceful descent to WHOLE NOTE tonic
                [('G5', 0.5), ('C5', 1.0)],                     # Grand leap to WHOLE NOTE resolution
                [('D5', 0.25), ('B4', 0.25), ('C5', 1.0)],      # Leading tone to WHOLE NOTE tonic
                [('E5', 0.5), ('C5', 1.0)],                     # Emphatic arrival on WHOLE NOTE
                [('C6', 0.5), ('C5', 1.0)],                     # Octave drop to WHOLE NOTE tonic
                [('B4', 0.25), ('C5', 1.25)],                   # Direct leading tone to VERY LONG tonic
                [('G5', 0.5), ('C5', 1.0)],                     # Fifth to WHOLE NOTE tonic
                [('F5', 0.25), ('E5', 0.25), ('C5', 1.0)],      # Suspension to WHOLE NOTE resolution
                [('D5', 0.5), ('C5', 1.0)],                     # Simple descent to WHOLE NOTE
                [('C5', 1.5)]                                    # Another sustained WHOLE BAR for variety
            ]
        }

        return data

    def generate_piece(self, seed: Optional[int] = None) -> List[Dict]:
        """
        Generate a complete piece by randomly selecting one variant for each bar.
        """
        if seed is not None:
            random.seed(seed)

        composition = []
        for bar_num in range(1, 15):
            variant_idx = random.randint(0, 10)
            composition.append(self._create_bar_data(bar_num, variant_idx))

        return composition

    def generate_with_dice(self) -> List[Dict]:
        """
        Generate using dice rolls (1-11) for each bar.
        """
        composition = []
        for bar_num in range(1, 15):
            roll = random.randint(1, 11)
            variant_idx = roll - 1
            bar_data = self._create_bar_data(bar_num, variant_idx)
            bar_data['roll'] = roll
            composition.append(bar_data)

        return composition

    def generate_with_choices(self, choices: List[int]) -> List[Dict]:
        """
        Generate a piece with specific variant choices for each bar.

        Args:
            choices: List of 14 integers (1-11) representing variant choice for each bar
        """
        if len(choices) != 14:
            raise ValueError("Must provide exactly 14 choices (one per bar)")

        if not all(1 <= c <= 11 for c in choices):
            raise ValueError("All choices must be between 1 and 11")

        composition = []
        for bar_num, choice in enumerate(choices, 1):
            variant_idx = choice - 1
            bar_data = self._create_bar_data(bar_num, variant_idx)
            bar_data['choice'] = choice
            composition.append(bar_data)

        return composition

    def _create_bar_data(self, bar_num: int, variant_idx: int) -> Dict:
        """Helper to create bar data dictionary."""
        bar_info = self.composition_data[bar_num]
        return {
            'bar': bar_num,
            'variant': variant_idx + 1,
            'harmony': bar_info['harmony'],
            'melody': bar_info['variants'][variant_idx],
            'chord_notes': bar_info['chord_notes']
        }

    def create_midi(self, composition: List[Dict], filename: str = "kirnberger_output.mid"):
        """
        Generate a MIDI file from the composition with melody and chord accompaniment.
        """
        if not MUSIC21_AVAILABLE:
            print("Error: music21 library not available. Cannot generate MIDI.")
            return False

        try:
            # Create a score with two parts (right hand melody, left hand accompaniment)
            score = stream.Score()

            # Right hand part (melody)
            melody_part = stream.Part()
            melody_part.id = 'Melody'
            melody_part.append(key.Key(self.key_signature))
            melody_part.append(meter.TimeSignature(self.time_signature))
            melody_part.append(tempo.MetronomeMark(number=120))

            # Left hand part (accompaniment)
            accomp_part = stream.Part()
            accomp_part.id = 'Accompaniment'
            accomp_part.append(key.Key(self.key_signature))
            accomp_part.append(meter.TimeSignature(self.time_signature))

            # Add notes from composition
            for bar_data in composition:
                bar_num = bar_data['bar']

                # Add melody notes with their specific durations
                for note_data in bar_data['melody']:
                    if isinstance(note_data, tuple):
                        note_name, duration = note_data
                    else:
                        # Fallback for old format
                        note_name, duration = note_data, 0.5
                    n = note.Note(note_name, quarterLength=duration)
                    melody_part.append(n)

                # Add chord accompaniment with CADENTIAL PROGRESSIONS
                chord_notes = bar_data['chord_notes']
                harmony = bar_data['harmony']

                # Enhanced accompaniment for CADENCES
                # Bar 5 (V before half cadence) - Add dominant 7th
                # Bar 13 (V before final cadence) - Add dominant 7th for stronger resolution
                if bar_num == 5 or bar_num == 13:
                    # Dominant 7th chord: G-B-D-F (in C major)
                    bass_note = chord_notes[0].replace('4', '3').replace('5', '3')  # G3
                    bass = note.Note(bass_note, quarterLength=0.75)
                    accomp_part.append(bass)

                    # V7 chord with 7th: G3-B3-D4-F4
                    chord_pitches = ['G3', 'B3', 'D4', 'F4']  # Dominant 7th
                    ch = chord.Chord(chord_pitches, quarterLength=0.75)
                    accomp_part.append(ch)

                # Bar 6 (I - half cadence resolution) - Strong tonic
                elif bar_num == 6:
                    bass_note = 'C3'  # Strong low C
                    bass = note.Note(bass_note, quarterLength=0.75)
                    accomp_part.append(bass)

                    # Full tonic chord with doubled root
                    chord_pitches = ['C3', 'E3', 'G3', 'C4']  # Strong tonic
                    ch = chord.Chord(chord_pitches, quarterLength=0.75)
                    accomp_part.append(ch)

                # Bar 12 (I6/4 - cadential 6/4) - Preparation for final cadence
                elif bar_num == 12:
                    bass_note = 'G3'  # G in bass (6/4 inversion)
                    bass = note.Note(bass_note, quarterLength=0.75)
                    accomp_part.append(bass)

                    # I6/4 chord: G-C-E
                    chord_pitches = ['G3', 'C4', 'E4']
                    ch = chord.Chord(chord_pitches, quarterLength=0.75)
                    accomp_part.append(ch)

                # Bar 14 (I - FINAL CADENCE) - Ultimate resolution with full chord
                elif bar_num == 14:
                    # Very strong bass - low C with long duration
                    bass_note = 'C2'  # Even lower for finality
                    bass = note.Note(bass_note, quarterLength=1.5)  # Full bar!
                    accomp_part.append(bass)

                    # NO additional chord - let the bass ring with melody for maximum clarity
                    # (The single low C with melody creates strongest ending)

                # All other bars - standard accompaniment
                else:
                    bass_note = chord_notes[0].replace('4', '3').replace('5', '3')
                    bass = note.Note(bass_note, quarterLength=0.75)
                    accomp_part.append(bass)

                    chord_pitches = [chord_notes[0].replace('4', '3').replace('5', '3'),
                                    chord_notes[1].replace('5', '4'),
                                    chord_notes[2].replace('5', '4')]
                    ch = chord.Chord(chord_pitches, quarterLength=0.75)
                    accomp_part.append(ch)

            score.append(melody_part)
            score.append(accomp_part)

            # Write MIDI file
            score.write('midi', fp=filename)
            print(f"[OK] MIDI file saved: {filename}")
            print(f"    - Melody + chord accompaniment included")
            return True

        except Exception as e:
            print(f"Error generating MIDI: {e}")
            import traceback
            traceback.print_exc()
            return False

    def create_score(self, composition: List[Dict], filename: str = "kirnberger_score.xml"):
        """
        Generate a MusicXML score file.
        """
        if not MUSIC21_AVAILABLE:
            print("Error: music21 library not available. Cannot generate score.")
            return False

        try:
            score = stream.Score()
            part = stream.Part()

            part.append(key.Key(self.key_signature))
            part.append(meter.TimeSignature(self.time_signature))
            part.append(tempo.MetronomeMark(number=120))

            for bar_data in composition:
                measure = stream.Measure()
                for note_data in bar_data['melody']:
                    if isinstance(note_data, tuple):
                        note_name, duration = note_data
                    else:
                        note_name, duration = note_data, 0.5
                    n = note.Note(note_name, quarterLength=duration)
                    measure.append(n)
                part.append(measure)

            score.append(part)
            score.write('musicxml', fp=filename)
            print(f"[OK] Score file saved: {filename}")
            return True

        except Exception as e:
            print(f"Error generating score: {e}")
            return False

    def print_composition(self, composition: List[Dict]):
        """Pretty print a generated composition."""
        print("=" * 70)
        print("KIRNBERGER'S MUSICAL DICE GAME - Generated Composition")
        print("=" * 70)
        print()

        print("PERIOD 1 (bars 1-6):")
        for item in composition[:6]:
            self._print_bar(item)

        print()
        print("PERIOD 2 (bars 7-14):")
        for item in composition[6:]:
            self._print_bar(item)

        print()
        print("=" * 70)

    def _print_bar(self, bar_data: Dict):
        """Helper to print a single bar."""
        variant_num = bar_data.get('variant') or bar_data.get('roll') or bar_data.get('choice')
        # Handle both tuple format (note, duration) and old string format
        melody_notes = []
        for note_data in bar_data['melody']:
            if isinstance(note_data, tuple):
                note_name, duration = note_data
                # Show duration as rhythm symbol
                if duration == 0.25:
                    rhythm = '♬'  # sixteenth
                elif duration == 0.5:
                    rhythm = '♪'  # eighth
                elif duration == 0.75:
                    rhythm = '♪.'  # dotted eighth
                elif duration == 1.0:
                    rhythm = '♩'  # quarter
                elif duration == 1.25:
                    rhythm = '♩.'  # dotted quarter (less common)
                elif duration == 1.5:
                    rhythm = '𝅗𝅥.'  # dotted quarter (full bar in 3/8)
                else:
                    rhythm = f'({duration})'
                melody_notes.append(f"{note_name}{rhythm}")
            else:
                melody_notes.append(note_data)
        melody_str = ' '.join(melody_notes)
        print(f"  Bar {bar_data['bar']:2d} | {bar_data['harmony']:6s} | "
              f"Variant {variant_num:2d} | {melody_str}")

    def save_composition(self, composition: List[Dict], filename: str = "composition.json"):
        """Save composition to JSON file."""
        with open(filename, 'w') as f:
            json.dump(composition, f, indent=2)
        print(f"[OK] Composition saved: {filename}")


def interactive_mode():
    """
    Interactive mode for generating compositions.
    """
    print("\n" + "="*70)
    print("KIRNBERGER'S MUSICAL DICE GAME - Interactive Mode")
    print("="*70)
    print()

    game = KirnbergerGame()

    while True:
        print("\nChoose an option:")
        print("  1. Generate random composition")
        print("  2. Roll dice for each bar")
        print("  3. Manually choose variants")
        print("  4. Generate with seed (reproducible)")
        print("  5. View statistics")
        print("  6. Exit")
        print()

        choice = input("Enter choice (1-6): ").strip()

        if choice == '1':
            print("\nGenerating random composition...")
            composition = game.generate_piece()
            game.print_composition(composition)

            if input("\nSave as MIDI? (y/n): ").lower() == 'y':
                filename = input("Filename (default: kirnberger_random.mid): ").strip()
                if not filename:
                    filename = "kirnberger_random.mid"
                game.create_midi(composition, filename)

            if input("Save as JSON? (y/n): ").lower() == 'y':
                filename = input("Filename (default: composition.json): ").strip()
                if not filename:
                    filename = "composition.json"
                game.save_composition(composition, filename)

        elif choice == '2':
            print("\nRolling dice for each bar...")
            composition = game.generate_with_dice()
            game.print_composition(composition)

            if input("\nSave as MIDI? (y/n): ").lower() == 'y':
                filename = input("Filename (default: kirnberger_dice.mid): ").strip()
                if not filename:
                    filename = "kirnberger_dice.mid"
                game.create_midi(composition, filename)

        elif choice == '3':
            print("\nManual variant selection")
            print("Enter your choice (1-11) for each bar:")
            choices = []

            for bar_num in range(1, 15):
                while True:
                    try:
                        bar_choice = input(f"  Bar {bar_num:2d} (1-11): ").strip()
                        bar_choice = int(bar_choice)
                        if 1 <= bar_choice <= 11:
                            choices.append(bar_choice)
                            break
                        else:
                            print("    Please enter a number between 1 and 11")
                    except ValueError:
                        print("    Please enter a valid number")

            composition = game.generate_with_choices(choices)
            game.print_composition(composition)

            if input("\nSave as MIDI? (y/n): ").lower() == 'y':
                filename = input("Filename (default: kirnberger_custom.mid): ").strip()
                if not filename:
                    filename = "kirnberger_custom.mid"
                game.create_midi(composition, filename)

        elif choice == '4':
            try:
                seed = int(input("\nEnter seed number: ").strip())
                print(f"Generating with seed {seed}...")
                composition = game.generate_piece(seed=seed)
                game.print_composition(composition)

                if input("\nSave as MIDI? (y/n): ").lower() == 'y':
                    filename = input(f"Filename (default: kirnberger_seed{seed}.mid): ").strip()
                    if not filename:
                        filename = f"kirnberger_seed{seed}.mid"
                    game.create_midi(composition, filename)
            except ValueError:
                print("Invalid seed number")

        elif choice == '5':
            print_statistics()

        elif choice == '6':
            print("\nThank you for using Kirnberger's Musical Dice Game!")
            break

        else:
            print("Invalid choice. Please try again.")


def print_statistics():
    """Print statistics about the game."""
    total = 11 ** 14
    print("\n" + "="*70)
    print("STATISTICS")
    print("="*70)
    print(f"Total bars: 14 (6 + 8)")
    print(f"Variants per bar: 11")
    print(f"Total possible compositions: {total:,}")
    print(f"Scientific notation: {total:.3e}")
    print()
    print("If you generated one composition per second:")
    seconds = total
    years = seconds / (60 * 60 * 24 * 365.25)
    print(f"  It would take {years:.2e} years to hear them all!")
    print(f"  That's about {years/13.8e9:.1f} times the age of the universe!")
    print("="*70)


def demo_mode():
    """Demonstration mode with pre-set examples."""
    print("Kirnberger's Musical Dice Game Generator")
    print("-" * 70)
    print()

    game = KirnbergerGame()

    # Example 1: Random composition
    print("EXAMPLE 1: Random Composition")
    print("-" * 70)
    composition1 = game.generate_piece(seed=42)
    game.print_composition(composition1)

    if MUSIC21_AVAILABLE:
        print("\nGenerating MIDI file...")
        game.create_midi(composition1, "kirnberger_example1.mid")

    print("\n\n")

    # Example 2: Dice rolls
    print("EXAMPLE 2: Dice Roll Composition")
    print("-" * 70)
    composition2 = game.generate_with_dice()
    game.print_composition(composition2)

    if MUSIC21_AVAILABLE:
        print("\nGenerating MIDI file...")
        game.create_midi(composition2, "kirnberger_example2.mid")

    print("\n\n")
    print_statistics()


def main():
    """Main entry point."""
    if not MUSIC21_AVAILABLE:
        print("\n[!] Warning: music21 not installed.")
        print("Install it for MIDI generation: py -m pip install music21\n")

    print("\nWelcome to Kirnberger's Musical Dice Game!")
    print()
    print("Choose mode:")
    print("  1. Demo mode (run examples)")
    print("  2. Interactive mode")
    print("  3. Quick random generation")
    print()

    mode = input("Enter choice (1-3, or press Enter for demo): ").strip()

    if mode == '2':
        interactive_mode()
    elif mode == '3':
        game = KirnbergerGame()
        composition = game.generate_piece()
        game.print_composition(composition)
        print()
        if MUSIC21_AVAILABLE and input("Generate MIDI? (y/n): ").lower() == 'y':
            game.create_midi(composition)
    else:
        demo_mode()


if __name__ == "__main__":
    main()
